# Generated by Django 5.0 on 2024-01-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='tank_capacity',
            new_name='fuel_tank_capacity',
        ),
    ]
